apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: golang433-hpa
  labels:
    app: golang433
    version: 0.0.1
    backstage.io/kubernetes-id: golang433
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: golang433
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75