---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: golang433-quota
  namespace: golang433
  labels:
    kubernetes.io/metadata.name: golang433
    backstage.io/kubernetes-id: golang433
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
